### ISSUE TITLE
lost connection?

### ISSUE THREAD

**Issue by fixopen** [ricklamers/gridstudio#95]
```
localhost:gridstudio mac$ ./run.sh
--> Updating terminal app.js
--> Run manager proxy, starting manager.go (compiling with go run ...)
Listening on port: 8080
WS Listening on port: 4430
Hashed PW: 19yxYLFN-1h1mow8cpqDqLlgsHo=
Login, found user matching hashed PW.
No uuid found, creating new WorkSession and processes
Create users session with UUID: 6aa0e528-db43-4b11-b4e8-1553f6e6bbfd.
1 user sessions active.
[Spawn] Tried creating processes GoCmd and NodeCmd
2019/09/04 06:57:21 http: panic serving 172.17.0.1:38280: runtime error: invalid memory address or nil pointer dereference
goroutine 162 [running]:
net/http.(*conn).serve.func1(0xc00022c0a0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x8918c0, 0xe37fa0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
main.destructSession(0xc0000de18e, 0x24, 0xc000076e10, 0xc000076e40)
	/home/source/proxy/manager.go:217 +0x128
main.main.func16(0x98c960, 0xc000150000, 0xc0000f2200)
	/home/source/proxy/manager.go:778 +0xfb
net/http.HandlerFunc.ServeHTTP(0xc00000e4a0, 0x98c960, 0xc000150000, 0xc0000f2200)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xe73d60, 0x98c960, 0xc000150000, 0xc0000f2200)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00007cd00, 0x98c960, 0xc000150000, 0xc0000f2200)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00022c0a0, 0x98d160, 0xc000054100)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
Tried destroying session 6aa0e528-db43-4b11-b4e8-1553f6e6bbfd, but sessions not in active usersessions.
0 user sessions active.
```

**Comment by fixopen** [comment]
first running, when I close workspace, show me "lost connection" message and terminals dump this message

**Comment by ricklamers** [comment]
Could you describe your setup? Are you using Docker on mac?

It's trying to destroy a session that apparently isn't actually active. Which is more of a warning then an actual error. I think you should try a clean install and see if the problem persists. If it does - feel free to re-open the ticket.
