### ISSUE TITLE
import mysql.connector failed

### ISSUE THREAD

**Issue by JohnnySung** [ricklamers/gridstudio#96]
I just installed mysql in  my mac, I used Python pip command to get it. Since Python2 will be depreciated soon, the website rejected me. So I used Python3 to pip it and executed "import mysql.connector" and no error happened. I tried to used Python2 back to execute "import mysql.connector" it gave me feedback:  
"Traceback (most recent call last):  File "<stdin>", line 1, in <module>"

In our beloved "gridstudio", seems Python2 is used, because when I stepped "import mysql.connector", it gave me the similar  File "<string>", line 1, in <module>" error!

How to change our gridstudio to Python3?

**Comment by ricklamers** [comment]
Grid Studio is using Python 3 exclusively. Are you sure you ran `python3 -m pip install mysql-connector-python`?
